language: generic
os: linux
dist: bionic

install:
    - sudo apt-get -y install lsb-core
    - sudo apt-get -y install docker.io

script:

    - ./test.sh
    - sudo systemctl unmask docker.service && sudo systemctl unmask docker.socket && sudo systemctl start docker.service
    - sudo docker version
