language: shell
os: linux
dist: bionic

install:
    - sudo apt-get -y install lsb-core
    - sudo apt-get -y install docker.io

script:
    ./test.sh
    sudo service docker restart
    sudo docker version
